version: '3.8'

services:
  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy
    ports:
      - "${HAPROXY_PORT_HTTP}:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - media-service
      - content-service

  media-service:
    build:
      context: ./media-service
    image: media-service:latest
    deploy:
      replicas: 13
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    environment:
      - CPU_LOAD_ITERATIONS=51000

  content-service:
    build:
      context: ./content-service
    image: content-service:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    environment:
      - CPU_LOAD_ITERATIONS=17000


  cadvisor:
    image: ghcr.io/google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - "/dev/kmsg:/dev/kmsg"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker/:/rootfs/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - '--housekeeping_interval=1s'
      - '--max_housekeeping_interval=1s'
      - '--docker_only=true'

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "${PROMETHEUS_PORT}:9090"
    depends_on:
      - cadvisor
      - haproxy

  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "${LOCUST_PORT}:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://haproxy
    depends_on:
      - haproxy

  dashboard-service:
    build:
      context: ./dashboard-service
    container_name: dashboard-service
    ports:
      - "3002:3002"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - PORT=3002
    depends_on:
      - prometheus

  brain-orchestrator:
    build:
      context: ./brain-orchestrator
    container_name: brain-orchestrator
    volumes:
      - ./dataset:/app/data:ro
      - ./models:/app/models:ro
      - ./:/app/compose
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - DASHBOARD_PREDICT_URL=http://dashboard-service:3002/api/predict
      - PRELOAD_CSV=/app/data/clarknet_features_30s.csv
      - COMPOSE_PROJECT_NAME=lstm-proactive-scaling-microservices-clarknet-docker-compose
      - COMPOSE_DIR=/app/compose
      - MODEL_PATH=/app/models/lstm_quantile_tau095_30s_7030.keras
      - FEAT_SCALER_PATH=/app/models/feat_scaler.pkl
      - TGT_SCALER_PATH=/app/models/tgt_scaler.pkl
    depends_on:
      - prometheus
      - dashboard-service
